config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :passwords, controller: 'clearance/passwords', only: %i[create new]
    resource :session, controller: 'clearance/sessions', only: [:create]

    resources :users, controller: 'clearance/users', only: [:create] do
      resource :password,
              controller: 'clearance/passwords',
              only: %i[create edit update]
    end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
    
    match 'blobs/:signed_id/*filename', to: 'blobs#show', via: [:get, :post]

    root 'static_pages#home'
    get 'static_pages/home', to: 'static_pages#home'

    resources :profiles, only: %i[index show]
    resources :questionnaire, only: %i[new create]
    get 'questionnaire/info', to: 'questionnaire#info'
    resources :posts, only: %i[index show]

    constraints Clearance::Constraints::SignedIn.new do
      comfy_route :cms_admin, path: "/admin/cms"
      comfy_route :blog_admin, path: "/admin/cms"
      get 'admin/profiles/search', to: 'admin/profiles#search',  defaults: { format: 'js' }

      namespace :admin do
        resources :profiles
        resources :dashboard, only: %i[index]
        resources :questionnaires, only: %i[index edit update destroy]
        resources :tags
        resources :post_tags
        resources :treatment_methods
        resources :posts
      end

      mount Tolk::Engine, at: 'admin/translations'
      mount Blazer::Engine, at: "/admin/statistics"
    end
    # Has to be defined last or it will make all other routes to be inaccessible.
    # comfy_route :blog, path: "/blog"
    comfy_route :cms, path: "/"
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class='section home'>
  <div class='container'>
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <div class="tile is-ancestor">
          <div class="tile is-parent is-8">
            <article class="tile is-child has-primary-border about-box">
              <p><%= t('.about.teaser') %></p>
              <%= link_to t('.about.button'), cms_link('about'), class: 'button is-primary' %>
            </article>
          </div>
          <div class="tile is-parent">
            <article class="tile is-child">
              <figure class="image">
                <%= image_tag("treatment_chair.png", :alt => "Illustration eines gynäkologischen Behandlungsstuhls", :title => "Illustration eines gynäkologischen Behandlungsstuhls, Fiona Tretau") %>
              </figure>
            </article>
          </div>
        </div>
        <div class="tile is-ancestor">
          <div class="tile is-parent m-t-lg">
            <article class="tile is-child has-danger-border cta-box">
              <p><%= t('.search.teaser') %></p>
              <%= link_to t('.search.button') , profiles_url, class: 'button is-danger' %>
            </article>
          </div>
          <div class="tile is-parent m-t-lg">
            <article class="tile is-child has-danger-border cta-box">
              <p><%= t('.recommend.teaser') %></p>
              <%= link_to t('.recommend.button'), new_questionnaire_url, class: 'button is-danger' %>
            </article>
          </div>
        </div>
        <div class="columns">
          <div class="column is-10 is-offset-1">
            <div class="tile is-ancestor">
              <%= link_to posts_path do %>
                <div class="tile is-parent m-t-lg">
                  <article class="tile is-child link-box has-primary-border">
                    <h2><%= t('.blog.headline') %></h2>
                    <p><%= t('.blog.teaser') %></p>
                  </article>
                </div>
              <% end %>
              <%= link_to cms_link('faq') do %>
                <div class="tile is-parent m-t-lg">
                  <article class="tile is-child link-box has-primary-border">
                    <h2><%= t('.faq.headline') %></h2>
                    <p><%= t('.faq.teaser') %></p>
                  </article>
                </div>
              <% end %>
              <%= link_to cms_link('glossary') do %>
                <div class="tile is-parent m-t-lg">
                  <article class="tile is-child link-box has-primary-border">
                    <h2><%= t('.glossar.headline') %></h2>
                    <p><%= t('.glossar.teaser') %></p>
                  </article>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>