config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :passwords, controller: 'clearance/passwords', only: %i[create new]
    resource :session, controller: 'clearance/sessions', only: [:create]

    resources :users, controller: 'clearance/users', only: [:create] do
      resource :password,
              controller: 'clearance/passwords',
              only: %i[create edit update]
    end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
    
    match 'blobs/:signed_id/*filename', to: 'blobs#show', via: [:get, :post]

    root 'static_pages#home'
    get 'static_pages/home', to: 'static_pages#home'

    resources :profiles, only: %i[index show]
    resources :questionnaire, only: %i[new create]
    get 'questionnaire/info', to: 'questionnaire#info'
    resources :posts, only: %i[index show]

    constraints Clearance::Constraints::SignedIn.new do
      comfy_route :cms_admin, path: "/admin/cms"
      comfy_route :blog_admin, path: "/admin/cms"
      get 'admin/profiles/search', to: 'admin/profiles#search',  defaults: { format: 'js' }

      namespace :admin do
        resources :profiles
        resources :dashboard, only: %i[index]
        resources :questionnaires, only: %i[index edit update destroy]
        resources :tags
        resources :post_tags
        resources :treatment_methods
        resources :posts
      end

      mount Tolk::Engine, at: 'admin/translations'
      mount Blazer::Engine, at: "/admin/statistics"
    end
    # Has to be defined last or it will make all other routes to be inaccessible.
    # comfy_route :blog, path: "/blog"
    comfy_route :cms, path: "/"
  end
end

app/views/shared/_post_detail_view.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <div class="content">
          <div class="post-detail">
            <div class="tags">
              <%= raw post.post_tags.map { |post_tag| raw(link_to(post_tag.name[I18n.locale.to_s], posts_path(post_tag: post_tag.key), class: 'tag is-medium'))}.join() %>
            </div>
            <p class="post-publish-date"><%= I18n.localize(post.publish_date, format: :long) %></p>
            <h1 class='title'><%= @post.title %></h1>
            <p class="teaser"><%= post.teaser %></p>
            <p class='author'><%= t('.from') %> <%= @post.author %></p>
            <% if @post.main_image.attached? %>
              <image src="<%=(url_for(@post.main_image))%>">
                <p><%= PostDecorator.new(post).display_title_credit %></p>
            <% end %>
            <p class='body'><%= @post.body %></p>
          </div>
        </div>
      </div>
    </div>
  </div> 
</section>

app/views/shared/_profile_detail_view.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2 m-b-xxl">
        <div class="content">
          <% if signed_in? %>
            <div class="has-danger-border m-b-md p-md">
              <h4><%= t('profile.internal_comment')%></h4>
              <p><%= profile.internal_comment.presence || '-' %></p>
              <h4><%= t('admin.profile.questionnaires')%></h4>
              <% profile.questionnaires.each.with_index(1) do |questionnaire, index| %>
                <%= link_to edit_admin_questionnaire_path(questionnaire) do %>
                  <%= index %>.
                  <span class="m-r-xs">
                    <i class="fa fa-file" title=<%= t('admin.profile.show') %>></i>
                  </span>
                <% end %>
              <% end %>
            </div>
          <% end %>
          <div class="profile-detail">
            <div class="questionnaire_count">
              <%= I18n.t('profile.questionnaire_count', :count => profile.questionnaires.count) %>
            </div>
            <h3><%= profile.first_name %> <%= profile.last_name %></h3>
            <p><%= I18n.t("profile.categories.#{profile.category}") %>
              <h4><%= t("profile.address") %></h4>
              <p><%= ProfileDecorator.new(profile).display_address %> <%= state_name(profile.state) %></p>
              <h4><%= t("profile.phone_number") %></h4>
              <p><%= link_to profile.phone_number, "tel:#{profile.phone_number}" %></p>
              <h4><%= t("profile.website") %></h4>
              <p><%= link_to(profile.website_with_protocol, profile.website_with_protocol, target: "_blank") %></p>
              <h4><%= t('profile.accessibility_addition')%></h4>
              <div class="m-b-md">
                <%= raw profile.accessibility_options.reject(&:blank?).map { |option| content_tag(:span, I18n.t("profile.barrier_free_access_options.#{option}"), class: 'tag is-medium')}.join(' ') %>
              </div>
              <p><%= profile.accessibility_addition %></p>
              <h4><%= t('profile.language')%></h4>
              <p><%= profile.language %></p>
              <h4><%= t('profile.health_insurance') %></h4>
              <div class="m-b-md">
                <%= raw profile.health_insurance.reject(&:blank?).map { |option| content_tag(:span, I18n.t("profile.health_insurance_options.#{option}"))}.join(',  ') %>
              </div>
              <h4><%= t('profile.recommended_for') %></h4>
              <div class="tags">
                <%= raw profile.tags.map(&:name).map { |tag_name| content_tag(:span, tag_name[I18n.locale.to_s], class: 'tag is-medium')}.join() %>
              </div>
              <h4><%= t('profile.treatment_methods') %></h4>
              <div class="tags">
                <%= raw profile.treatment_methods.map(&:name).map { |treatment_method_name| content_tag(:span, treatment_method_name[I18n.locale.to_s], class: 'tag is-medium')}.join() %>
              </div>
              <h4><%= t('profile.financing_of_treatments')%></h4>
              <p><%= profile.financing_of_treatments %></p>
              <h4><%= t('profile.comment')%></h4>
              <% profile.comments.each do |comment| %>
                <blockquote><%= comment.content %></blockquote>
              <% end %>
              <p class="has-text-right is-italic"><%= t('profile.last_updated')%>: <%= I18n.l(profile.updated_at, format: :short) %></p>
            </div>
          </div>
          <% if signed_in? %>
            <%= link_to t('profile.edit'), edit_admin_profile_path(profile.id), class: 'button is-danger' %>
          <% end %>
        </div>
      </div>
    </section>