config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :passwords, controller: 'clearance/passwords', only: %i[create new]
    resource :session, controller: 'clearance/sessions', only: [:create]

    resources :users, controller: 'clearance/users', only: [:create] do
      resource :password,
              controller: 'clearance/passwords',
              only: %i[create edit update]
    end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
    
    match 'blobs/:signed_id/*filename', to: 'blobs#show', via: [:get, :post]

    root 'static_pages#home'
    get 'static_pages/home', to: 'static_pages#home'

    resources :profiles, only: %i[index show]
    resources :questionnaire, only: %i[new create]
    get 'questionnaire/info', to: 'questionnaire#info'
    resources :posts, only: %i[index show]

    constraints Clearance::Constraints::SignedIn.new do
      comfy_route :cms_admin, path: "/admin/cms"
      comfy_route :blog_admin, path: "/admin/cms"
      get 'admin/profiles/search', to: 'admin/profiles#search',  defaults: { format: 'js' }

      namespace :admin do
        resources :profiles
        resources :dashboard, only: %i[index]
        resources :questionnaires, only: %i[index edit update destroy]
        resources :tags
        resources :post_tags
        resources :treatment_methods
        resources :posts
      end

      mount Tolk::Engine, at: 'admin/translations'
      mount Blazer::Engine, at: "/admin/statistics"
    end
    # Has to be defined last or it will make all other routes to be inaccessible.
    # comfy_route :blog, path: "/blog"
    comfy_route :cms, path: "/"
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :profiles, through: :taggings

  has_many :questionnaire_taggings, dependent: :destroy
  has_many :questionnaires, through: :questionnaire_taggings

  store_accessor :name, :de, :en

  validates :en, presence: true
  validates :de, presence: true
end

app/controllers/admin/tags_controller.rb
# frozen_string_literal: true

class Admin::TagsController < ApplicationController
  layout 'admin'

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.key = parameterize_en_name
    if @tag.save
      redirect_to admin_tags_path
    else
      render 'new'
    end
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:success] = 'Tag updated'
      redirect_to admin_tags_path
    else
      render 'edit'
    end
  end

  private

  def tag_params
    params.require(:tag)
          .permit(:name, :de, :en)
  end

  def parameterize_en_name
    params[:tag][:en].parameterize(separator: '_')
  end
end

app/helpers/admin/tags_helper.rb
# frozen_string_literal: true

module Admin::TagsHelper
end

app/views/admin/tags/_form.html.erb
<%= form_for tag, url: yield(:resource_path) do |form| %>
  <% if tag.errors.any? %>
    <div class="notification is-danger">
      <ul>
        <% tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <div class="control">
      <%= form.label :de %>
      <%= form.text_field :de, class: 'input' %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= form.label :en %>
      <%= form.text_field :en, class: 'input' %>
    </div>
  </div>
  <div class="control">
    <%= form.submit t('.save'), class: 'button is-primary' %>
  </div>
<% end %>

app/views/admin/tags/edit.html.erb
<% provide(:resource_path, admin_tag_path) %>
<div class="section">
  <div class="container">
    <h2 class="title"><%= t('.headline') %></h2>
    <%= render partial: "form", locals: {tag: @tag} %>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class='section'>
  <div class='container'>
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <%= link_to t('admin.new_tag'), new_admin_tag_path, class: 'button is-primary' %>
        <table class='table is-fullwidth'>
          <thead>
            <tr>
              <th><%=t('admin.tags.name')%></th>
              <th><%=t('admin.tags.edit.headline')%></th>
            </tr>
          </thead>
          <tbody>
            <% @tags.each do |tag| %>
              <tr>
                <td><%= tag.name[I18n.locale.to_s] %></td>
                <td><%= link_to t('profile.edit'), edit_admin_tag_path(tag.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/tags/new.html.erb
<% provide(:resource_path, admin_tags_path) %>
<div class='container'>
  <div class="columns">
    <div class="column is-10 is-offset-1">
     <h2 class="title"><%= I18n.t('admin.tags.new.headline') %></h2>
        <%= render partial: "form", locals: {tag: @tag} %>
      </div>
    </div>
  </div>