config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :passwords, controller: 'clearance/passwords', only: %i[create new]
    resource :session, controller: 'clearance/sessions', only: [:create]

    resources :users, controller: 'clearance/users', only: [:create] do
      resource :password,
              controller: 'clearance/passwords',
              only: %i[create edit update]
    end

    get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
    delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
    
    match 'blobs/:signed_id/*filename', to: 'blobs#show', via: [:get, :post]

    root 'static_pages#home'
    get 'static_pages/home', to: 'static_pages#home'

    resources :profiles, only: %i[index show]
    resources :questionnaire, only: %i[new create]
    get 'questionnaire/info', to: 'questionnaire#info'
    resources :posts, only: %i[index show]

    constraints Clearance::Constraints::SignedIn.new do
      comfy_route :cms_admin, path: "/admin/cms"
      comfy_route :blog_admin, path: "/admin/cms"
      get 'admin/profiles/search', to: 'admin/profiles#search',  defaults: { format: 'js' }

      namespace :admin do
        resources :profiles
        resources :dashboard, only: %i[index]
        resources :questionnaires, only: %i[index edit update destroy]
        resources :tags
        resources :post_tags
        resources :treatment_methods
        resources :posts
      end

      mount Tolk::Engine, at: 'admin/translations'
      mount Blazer::Engine, at: "/admin/statistics"
    end
    # Has to be defined last or it will make all other routes to be inaccessible.
    # comfy_route :blog, path: "/blog"
    comfy_route :cms, path: "/"
  end
end

app/models/questionnaire.rb
# frozen_string_literal: true

class Questionnaire < ApplicationRecord
  include Filterable

  attribute :status, :integer, default: 1
  has_many :answers, dependent: :destroy
  has_many :questionnaire_taggings, dependent: :destroy
  has_many :tags, through: :questionnaire_taggings
  has_many :questionnaire_treatments, dependent: :destroy
  has_many :treatment_methods, through: :questionnaire_treatments
  belongs_to :profile, optional: true
  enum status: { new: 1, check_1_completed: 2, consultation_required: 4,
                 profile_published: 5, in_progress: 6,
                 inquired_about_abortion: 7, rejected: 8 }, _prefix: :status

  default_scope { order(created_at: :desc) }
  scope :filter_by_status, ->(status) { where status: }
  scope :filter_by_last_name, lambda { |last_name|
                                includes(:answers)
                                  .where('answers.key' => 'last_name')
                                  .where('lower(answers.content::text) like ?',
                                         "%#{last_name.downcase}%")
                              }

  def treating_persons_name
    return unless names_present?

    answers.find_by(key: 'first_name').content << ' ' <<
      answers.find_by(key: 'last_name').content
  end

  def answer(key)
    answer = answers.find_by(key:) || NullAnswer.new(key)
    answer.content
  end

  private

  def names_present?
    answers.find_by(key: 'first_name') &&
      answers.find_by(key: 'last_name')
  end
end

app/models/questionnaire_form.rb
# frozen_string_literal: true

class QuestionnaireForm
  include ActiveModel::Model
  ATTRIBUTES = %i[first_name last_name category street zip_code
                  city state website_with_protocol payments_required_for_specific_treatments
                  languages barrier_free_access_options
                  barrier_free_access amount_of_visits health_insurance
                  self_describing_tags recommended_treatments treatment_rejected
                  financing_of_treatments listening consent
                  examination_execution treated_with_respect
                  discriminatory_remarks respect_anything_else feedback
                  additional_self_describing_tags explanation_of_treatment
                  additional_recommended_treatments practice_staff
                  limit_recommendation phone_number treatment_method_ids tag_ids].freeze

  attr_accessor *ATTRIBUTES

  def save
    return false if invalid?

    create_questionnaire
    true
  end

  private

  def create_questionnaire
    ActiveRecord::Base.transaction do
      questionnaire = Questionnaire.new
      ATTRIBUTES.each do |attribute|
        next unless attribute.to_s != 'tag_ids' && attribute.to_s != 'treatment_method_ids'

        questionnaire.answers.build(
          key: attribute.to_s, content: method(attribute).call
        )
      end
      questionnaire.save!

      create_taggings(questionnaire)
      create_treatments(questionnaire)
    end
  end

  def create_taggings(questionnaire)
    tag_ids = tags

    return if tag_ids.blank?

    tag_ids.compact_blank.each do |id|
      questionnaire.questionnaire_taggings.create!(tag_id: id)
    end
  end

  def create_treatments(questionnaire)
    treatment_method_ids = treatment_methods

    return if treatment_method_ids.blank?

    treatment_method_ids.compact_blank.each do |id|
      questionnaire.questionnaire_treatments.create!(treatment_method_id: id)
    end
  end

  def tags
    method('tag_ids').call
  end

  def treatment_methods
    method('treatment_method_ids').call
  end
end

app/controllers/admin/questionnaires_controller.rb
# frozen_string_literal: true

class Admin::QuestionnairesController < ApplicationController
  layout 'admin'

  def index
    @pagy, @questionnaires = pagy(
      Questionnaire.filter(params.slice(:status, :last_name))
    )
  end

  def edit
    @questionnaire = Questionnaire.find(params[:id])
  end

  def update
    @questionnaire = Questionnaire.find(params[:id])
    if @questionnaire.update(questionnaire_params)
      flash[:success] = 'Questionnaire updated'
      redirect_to edit_admin_questionnaire_path(@questionnaire)
    else
      render 'edit'
    end
  end

  def destroy
    @questionnaire = Questionnaire.find(params[:id])
    @questionnaire.destroy
    redirect_to admin_questionnaires_path
  end

  private

  def questionnaire_params
    params.require(:questionnaire).permit(
      :status,
      :comment,
      :profile_id,
      :tag,
      { tag_ids: [] },
      :tag_ids,
      :treatment_method_id,
      { treatment_method_ids: [] },
      :treatment_method_ids
    )
  end
end

app/controllers/questionnaire_controller.rb
# frozen_string_literal: true

class QuestionnaireController < ApplicationController
  invisible_captcha only: %i[create], honeypot: :subtitle

  def new
    @questionnaire_form = QuestionnaireForm.new
  end

  def create
    @questionnaire_form = QuestionnaireForm.new(questionnaire_form_params)
    if @questionnaire_form.save
      redirect_to questionnaire_info_path
    else
      render :new
    end
  end

  def info; end

  def questionnaire_form_params
    params.require(:questionnaire_form).permit(
      :first_name, :last_name, :category, :street, :zip_code, :city,
      :state, :website_with_protocol, :languages, :payments_required_for_specific_treatments,
      :treatment_rejected, :phone_number,
      :respect_anything_else, :feedback, :barrier_free_access, :amount_of_visits,
      :practice_staff, :limit_recommendation,
      :additional_recommended_treatments, :additional_self_describing_tags,
      examination_execution: [], treated_with_respect: %i[boolean comment],
      discriminatory_remarks: %i[boolean comment],
      explanation_of_treatment: %i[boolean comment],
      listening: %i[boolean comment], consent: %i[boolean comment],
      financing_of_treatments: %i[boolean comment],
      self_describing_tags: [], recommended_treatments: [], health_insurance: [],
      barrier_free_access_options: [],
      tag_ids: [], treatment_method_ids: []
    )
  end
end

app/helpers/admin/questionnaires_helper.rb
# frozen_string_literal: true

module Admin::QuestionnairesHelper
  def formatted_tags(collection, translation_key)
    return if collection.blank?

    collection.compact_blank.map do |tag_name|
      tag.span(t("questionnaire_form.#{translation_key}.#{tag_name}"), class: 'tag')
    end.join
  end

  def format_examination_execution(content)
    return if content.blank?

    content.compact_blank.map do |answer|
      tag.li(t("questionnaire_form.examination_execution.#{answer}"))
    end.join
  end

  def format_health_insurance(content)
    return if content.blank?

    content.compact_blank.map do |answer|
      tag.span(t("admin.questionnaires.edit.health_insurance_options.#{answer}"))
    end.join(', ')
  end

  def format_boolean_and_comment_answer(answer)
    return if answer.blank?

    answer.to_a.map do |key, value|
      tag.li("#{t(".answer_type.#{key}")}: #{value}")
    end.join
  end

  def options_for_status
    {
      t('.status.all') => nil,
      t('.status.new') => :new,
      t('.status.in_progress') => :in_progress,
      t('.status.check_1_completed') => :check_1_completed,
      t('.status.consultation_required') => :consultation_required,
      t('.status.profile_published') => :profile_published,
      t('.status.rejected') => :rejected,
      t('.status.inquired_about_abortion') => :inquired_about_abortion
    }
  end
end

app/helpers/questionnaire_helper.rb
# frozen_string_literal: true

module QuestionnaireHelper
  def insurance_options
    {
      statutory: t('questionnaire_form.statutory'),
      private: t('questionnaire_form.private'),
      unknown: t('questionnaire_form.unknown')
    }
  end

  def tag_list
    {
      fgmc: t('questionnaire_form.tags.fgmc'),
      non_binary: t('questionnaire_form.tags.non_binary'),
      trans: t('questionnaire_form.tags.trans'),
      trans_masculinity: t('questionnaire_form.tags.trans_masculinity'),
      trans_femininity: t('questionnaire_form.tags.trans_femininity'),
      masculine_read: t('questionnaire_form.tags.masculine_read'),
      inter: t('questionnaire_form.tags.inter'),
      black_people: t('questionnaire_form.tags.black_people'),
      poc: t('questionnaire_form.tags.poc'),
      indigenous: t('questionnaire_form.tags.indigenous'),
      jewish: t('questionnaire_form.tags.jewish'),
      mentally_retarded: t('questionnaire_form.tags.mentally_retarded'),
      migrant: t('questionnaire_form.tags.migrant'),
      muslim: t('questionnaire_form.tags.muslim'),
      neurodivers: t('questionnaire_form.tags.neurodivers'),
      physically_disabled: t('questionnaire_form.tags.physically_disabled'),
      roma: t('questionnaire_form.tags.roma'),
      gay_bi_or_pan: t('questionnaire_form.tags.gay_bi_or_pan'),
      asexual: t('questionnaire_form.tags.asexual'),
      polyamorous: t('questionnaire_form.tags.polyamorous'),
      sex_worker: t('questionnaire_form.tags.sex_worker'),
      single_parent: t('questionnaire_form.tags.single_parent'),
      childfree_by_choice: t('questionnaire_form.tags.childfree_by_choice'),
      drug_user: t('questionnaire_form.tags.drug_user'),
      fat: t('questionnaire_form.tags.fat'),
      thin: t('questionnaire_form.tags.thin'),
      hiv_positive: t('questionnaire_form.tags.hiv_positive'),
      chronically_ill: t('questionnaire_form.tags.chronically_ill'),
      mental_illness: t('questionnaire_form.tags.mental_illness'),
      sexual_violence: t('questionnaire_form.tags.sexual_violence')
    }
  end

  def treatments_list
    {
      abortion_dileation: t('questionnaire_form.treatments.abortion_dileation'),
      abortion_aspiration: t('questionnaire_form.treatments.abortion_aspiration'),
      abortion_medication: t('questionnaire_form.treatments.abortion_medication'),
      contraception_methods: t('questionnaire_form.treatments.contraception_methods'),
      copper_chain_insertion: t('questionnaire_form.treatments.copper_chain_insertion'),
      spiral_insertion: t('questionnaire_form.treatments.spiral_insertion'),
      sterilization: t('questionnaire_form.treatments.sterilization'),
      transition: t('questionnaire_form.treatments.transition'),
      transition_hormone_therapy: t('questionnaire_form.treatments.transition_hormone_therapy'),
      neo_vagina: t('questionnaire_form.treatments.neo_vagina'),
      metoidioplasty: t('questionnaire_form.treatments.metoidioplasty'),
      people_with_penis: t('questionnaire_form.treatments.people_with_penis'),
      mastectomy: t('questionnaire_form.treatments.mastectomy'),
      breast_augmentation: t('questionnaire_form.treatments.breast_augmentation'),
      pregnancy: t('questionnaire_form.treatments.pregnancy'),
      miscarriage: t('questionnaire_form.treatments.miscarriage'),
      midwives_cooperation:
      t('questionnaire_form.treatments.midwives_cooperation'),
      out_of_hospital_births:
      t('questionnaire_form.treatments.out_of_hospital_births'),
      breastfeeding: t('questionnaire_form.treatments.breastfeeding'),
      chestfeeding: t('questionnaire_form.treatments.chestfeeding'),
      birth_preparation_classes_non_heteronormative:
      t('questionnaire_form.treatments.birth_preparation_classes_non_heteronormative'),
      birth_preparation_classes_single_parent:
      t('questionnaire_form.treatments.birth_preparation_classes_single_parent'),
      unfulfilled_desire_children_hetero:
      t('questionnaire_form.treatments.unfulfilled_desire_children_hetero'),
      unfulfilled_desire_children_queer:
      t('questionnaire_form.treatments.unfulfilled_desire_children_queer'),
      unfulfilled_desire_children_singles:
      t('questionnaire_form.treatments.unfulfilled_desire_children_singles'),
      alternative_treatments:
      t('questionnaire_form.treatments.alternative_treatments'),
      breast_disease: t('questionnaire_form.treatments.breast_disease'),
      cancer: t('questionnaire_form.treatments.cancer'),
      dealing_with_sexualized_violence:
      t('questionnaire_form.treatments.dealing_with_sexualized_violence'),
      endometriosis: t('questionnaire_form.treatments.endometriosis'),
      incontinence: t('questionnaire_form.treatments.incontinence'),
      routine_treatment: t('questionnaire_form.treatments.routine_treatment'),
      initial_treatment: t('questionnaire_form.treatments.initial_treatment'),
      menopause: t('questionnaire_form.treatments.menopause'),
      menstrual_symptoms: t('questionnaire_form.treatments.menstrual_symptoms'),
      mental_counseling: t('questionnaire_form.treatments.mental_counseling'),
      sexual_dysfunction: t('questionnaire_form.treatments.sexual_dysfunction'),
      std: t('questionnaire_form.treatments.std'),
      std_test: t('questionnaire_form.treatments.std_test'),
      vaginism: t('questionnaire_form.treatments.vaginism'),
      hormonal_expertise: t('questionnaire_form.treatments.hormonal_expertise'),
      dysplasia_consultation: t('questionnaire_form.treatments.dysplasia_consultation'),
      conization: t('questionnaire_form.treatments.conization'),
      cryopreservation: t('questionnaire_form.treatments.cryopreservation')
    }
  end

  def barrier_free_access_options_list
    {
      wheelchair_access: t('questionnaire_form.barrier_free_access_options.wheelchair_access'),
      orientation_aids: t('questionnaire_form.barrier_free_access_options.orientation_aids'),
      sign_language: t('questionnaire_form.barrier_free_access_options.sign_language'),
      easy_language_html: t('questionnaire_form.barrier_free_access_options.easy_language_html'),
      appointments_online: t('questionnaire_form.barrier_free_access_options.appointments_online'),
      appointments_phone: t('questionnaire_form.barrier_free_access_options.appointments_phone'),
      website_usable_with_screenreader:
      t('questionnaire_form.barrier_free_access_options.website_usable_with_screenreader')
    }
  end

  def boolean_options
    {
      yes: t('questionnaire_form.answer_yes'),
      no: t('questionnaire_form.answer_no')
    }
  end

  def financing_of_treatment_options
    {
      yes: t('questionnaire_form.answer_yes'),
      no: t('questionnaire_form.answer_no'),
      not_applicable: t('questionnaire_form.answer_not_applicable')
    }
  end

  def examination_execution_options
    {
      examine_yourself:
      t('questionnaire_form.examination_execution.examine_yourself'),
      lateral_position:
      t('questionnaire_form.examination_execution.lateral_position'),
      stay_clothed: t('questionnaire_form.examination_execution.stay_clothed')
    }
  end

  def category_options
    {
      t('questionnaire_form.category.gynecologist') => :gynecologist,
      t('questionnaire_form.category.general_practitioner') =>
      :general_practitioner,
      t('questionnaire_form.category.midwife') => :midwife,
      t('questionnaire_form.category.endocrinologist') => :endocrinologist,
      t('questionnaire_form.category.urologist') => :urologist,
      t('questionnaire_form.category.dermatologist') => :dermatologist
    }
  end
end

app/views/admin/questionnaires/_filter_bar.html.erb
<section role='search'>
  <fieldset>
    <%= form_with url: admin_questionnaires_path, method: 'get', id: 'js-turbolinks-get-form' do |form| %>
      <div class="field is-grouped is-horizontal m-b-md">
        <div class="control">
          <div class='select'>
            <%= form.select(:status, options_for_status, selected: params[:status]) %>
          </div>
        </div>
        <div class="control">
          <%= form.text_field :last_name, class: 'input', placeholder: t('.placeholder_last_name'), value: params[:last_name]  %>
        </div>
        <div class="control">
          <%= form.submit t('.filter'), class: 'button is-primary' %>
        </div>
      </div>
    <% end %>
  </fieldset>
</section>

app/views/admin/questionnaires/_profile_search_result.html.erb
<% if @profiles.empty? %>
  No results
<% else %>
  <ul>
    <% @profiles.each do |profile| %>
      <li>
        <%= profile.first_name %> <%= profile.last_name %>, <%= profile.city %>
        <%= link_to admin_questionnaire_path(params[:questionnaire_id], questionnaire: { profile_id: profile.id }), remote: true, id: 'link_profile_link', method: 'patch' do %>
          <span class="icon">
            <i class="fa fa-plus" aria-hidden="true" title='Link Profile'></i>
          </span>
        <% end %>
        <%= link_to admin_profile_path(profile.id), data: { test: "show-profile-link" } do %>
          <span class="icon">
            <i class="fa fa-eye" title=<%= t('profile.show') %>></i>
          </span>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admin/questionnaires/edit.html.erb
<section class="section questionnaire">
  <div class="container content">
    <div class="columns">
      <div class="is-offset-1 column is-5 box">
        <%= form_for @questionnaire, url: admin_questionnaire_path, class: 'box' do |form| %>
          <div class="field">
            <label class="label">Status</label>
            <div class="select">
              <%= form.select(:status, options_for_status) %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= form.label :comment %>
              <%= form.text_area :comment, class: 'textarea' %>
            </div>
          </div>
          <div class="field">
            <div class="control">
              <%= form.submit t('.save'), class: 'button is-primary' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="column is-5 box">
        <label class="label"><%= t('.search_profiles') %></label>
        <%= form_with url: admin_profiles_search_path, method: 'get' do |form| %>
          <%= form.hidden_field :questionnaire_id,  value: @questionnaire.id %>
          <div class="field is-grouped is-horizontal">
            <div class="control">
              <%= form.text_field :last_name, class: 'input', placeholder: t('.search_profiles_by_lastname'), value: params[:last_name]  %>
            </div>
            <div class="control">
              <%= form.submit I18n.t('profile.filter'), class: 'button is-primary' %>
            </div>
          </div>
        <% end %>
        <div class="profile-search-result" id="search-result">
        </div>
        <div class="linked-profile m-t-lg">
          <label class="label"><%= t('.linked_profile') %></label>
          <% if @questionnaire.profile_id %>
            <%= link_to profile_display_name(@questionnaire.profile_id), admin_profile_path(@questionnaire.profile_id), id: "linked_profile" %>
          <% else %>
            - 
          <% end %>
        </div>
        <div class="new-profile m-t-lg">
          <%= link_to t('admin.new_profile'), new_admin_profile_path(:questionnaire_id => @questionnaire.id), class: 'button is-primary' %>
        </div>
      </div>
    </div>
    <div class="columns">
      <div class="column is-offset-1 is-10 box">
        <h2><%= t('.about_treating_person') %></h2>
        <p><%= @questionnaire.answer("first_name") %> <%= @questionnaire.answer("last_name")%></p>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_address %> <%= state_name(@questionnaire.answer('state')) %></p>
        <h3 class="is-size-6"><%= t('.website') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('website_with_protocol') %></p>
        <h3 class="is-size-6"><%= t('.phone_number') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('phone_number') %></p>
        <h3 class="is-size-6"><%= t('.category') %></h3>
        <p data-test="display-selected-category"><%= @questionnaire.answer("category").present? ? t("profile.categories.#{@questionnaire.answer("category")}") : "-" %></p>
        <h3 class="is-size-6"><%= t('.health_insurance') %></h3>
        <p><%= raw format_health_insurance(@questionnaire.answer("health_insurance")) %></p>
        <h3 class="is-size-6"><%= t('.financing_of_treatments') %></h3>
        <ul><%= raw format_boolean_and_comment_answer(@questionnaire.answer('financing_of_treatments')) %></ul>
        <h3 class="is-size-6"><%= t('.payments_required_for_specific_treatments') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('payments_required_for_specific_treatments') %></p>
        <h3 class="is-size-6"><%= t('.languages') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('languages') %></p>
        <h3 class="is-size-6"><%= t('.practice_staff') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('practice_staff') %></p>
        <h3 class="is-size-6"><%= t('.barrier_free_access_options') %> </h3>
        <p><%= raw formatted_tags(@questionnaire.answer('barrier_free_access_options'), 'barrier_free_access_options') %></p>
        <h3 class="is-size-6"><%= t('.barrier_free_access') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('barrier_free_access') %></p>
        <h3 class="is-size-6"><%= t('.amount_of_visits') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('amount_of_visits') %></p>
        <h2><%= t('.submitting_person') %></h2>
        <h3 class="is-size-6"><%= t('.tags') %></h3>
        <div class="tags">
          <%= raw @questionnaire.tags.map(&:name).map { |tag_name| content_tag(:span, tag_name[I18n.locale.to_s], class: 'tag is-medium')}.join() %>
        </div>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('additional_self_describing_tags') %></p>
        <h3 class="is-size-6"><%= t('.limit_recommendation') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('limit_recommendation') %></p>
        <h2><%= t('.treatment_methods') %></h2>
        <h3 class="is-size-6"><%= t('.recommended_treatments') %> </h3>
        <div class="tags">
          <%= raw @questionnaire.treatment_methods.map(&:name).map { |treatment_method_name| content_tag(:span, treatment_method_name[I18n.locale.to_s], class: 'tag is-medium')}.join() %>
        </div>
        <h3 class="is-size-6"><%= t('.additional_recommended_treatments') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('additional_recommended_treatments') %></p>
        <h3 class="is-size-6"><%= t('.treatment_rejected') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('treatment_rejected') %></p>
        <h2><%= t('.respectful_treatment') %></h2>
        <h3 class="is-size-6"><%= t('.listening') %></h3>
        <ul><%= raw format_boolean_and_comment_answer(@questionnaire.answer('listening')) %></ul>
        <h3 class="is-size-6"><%= t('.consent') %></h3>
        <ul><%= raw format_boolean_and_comment_answer(@questionnaire.answer('consent')) %></ul>
        <h3 class="is-size-6"><%= t('.explanation_of_treatment') %></h3>
        <ul><%= raw format_boolean_and_comment_answer(@questionnaire.answer('explanation_of_treatment')) %></ul>
        <h3 class="is-size-6"><%= t('.examination_execution') %></h3>
        <ul><%= raw format_examination_execution(@questionnaire.answer('examination_execution')) %></ul>
        <h3 class="is-size-6"><%= t('.treated_with_respect') %></h3>
        <ul><%= raw format_boolean_and_comment_answer(@questionnaire.answer('treated_with_respect')) %></ul>
        <h3 class="is-size-6"><%= t('.discriminatory_remarks') %></h3>
        <ul><%= raw format_boolean_and_comment_answer(@questionnaire.answer('discriminatory_remarks')) %></ul>
        <h3 class="is-size-6"><%= t('.respect_anything_else') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('respect_anything_else') %></p>
        <h2><%= t('.feedback') %></h2>
        <h3 class="is-size-6"><%= t('.feedback') %></h3>
        <p><%= QuestionnaireDecorator.new(@questionnaire).display_answer('feedback') %></p>
      </div>
    </div>
  </div>
</div>
</section>

app/views/admin/questionnaires/index.html.erb
<div class='section'>
  <div class='container'>
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <%= render 'filter_bar' %>
        <table class='table is-fullwidth'>
          <thead>
            <tr>
              <th><%=t('.treating_persons_name')%></th>
              <th><%=t('.status')%></th>
              <th><%=t('.created_profile')%></th>
              <th><%=t('.date')%></th>
              <th><%=t('.actions') %></th>
            </tr>
          </thead>
          <tbody>
            <% @questionnaires.each do |questionnaire| %>
              <tr>
                <td><%= questionnaire.treating_persons_name.presence %></td>
                <td><%= t("admin.questionnaires.edit.status.#{questionnaire.status}") %></td>
                <% if questionnaire.profile_id.blank? %>
                  <td> - </td>
                <% else %>
                  <td><%= link_to 'Profile', admin_profile_path(questionnaire.profile_id) %></td>
                <% end %>
                <td><%= questionnaire.created_at.to_formatted_s(:short) %></td>
                <td>
                  <%= link_to edit_admin_questionnaire_path(questionnaire.id) do %>
                    <span class="icon">
                      <i class="fa fa-eye" title=<%= t('.show') %>></i>
                    </span>
                  <% end %>
                  <%= link_to admin_questionnaire_path(questionnaire.id), method: :delete, data: { confirm: t('.confirm') } do %>
                    <span class="icon">
                      <i class="fa fa-trash" title=<%= t('.delete') %>></i>
                    </span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div>
          <%= pagy_bulma_nav(@pagy).html_safe if @pagy.pages > 1 %>
        </div>
      </div>
    </div>
  </div>
</div>